### ISSUE TITLE
Proclamation of death let's the player select the monster to destroy instead of the opponent

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#10]
![image](https://user-images.githubusercontent.com/37833135/55683215-a6555c80-593d-11e9-813e-f0107b853f86.png)

(This happened when it was activated as a shield trigger. Haven't tested activating it normally yet.)

**Comment by Hello23-Ygopro** [comment]
This is similar to _Terradragon Gamiratar_. #8 I need to fix all the appropriate `Auxiliary` functions so this kind of issue doesn't happen again.

**Comment by szefo09** [comment]
From a quick test it seems like it’s fixed now, thank you. I’ll update you if I notice it again.
