### ISSUE TITLE
When Necrodragon Galbazeek attacks when the player controlls no shields it shows an error message in log.

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#11]
![image](https://user-images.githubusercontent.com/37833135/55683248-0ba94d80-593e-11e9-80ec-414f09c56797.png)
![image](https://user-images.githubusercontent.com/37833135/55683251-0d731100-593e-11e9-94cd-a3280789c3f1.png)

ID of the card: 24008032

Propably missing a check if a variable is not nil

**Comment by Hello23-Ygopro** [comment]
I also got an error when there were no cards left to select. See if you still get an error starting from this fix: https://github.com/Hello23-Ygopro/ygopro-dm/commit/5dae07632bf8c566b8852151dffa0a9fc3681438

**Comment by Hello23-Ygopro** [comment]
I also got an error when there were no cards left to select. See if you still get an error starting from this fix: https://github.com/Hello23-Ygopro/ygopro-dm/commit/5dae07632bf8c566b8852151dffa0a9fc3681438

**Comment by Hello23-Ygopro** [comment]
I also got an error when there were no cards left to select. See if you still get an error starting from using this fix: https://github.com/Hello23-Ygopro/ygopro-dm/commit/5dae07632bf8c566b8852151dffa0a9fc3681438
