### ISSUE TITLE
Evolution script error.

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#13]
After one of your commits evolution broke.
![image](https://user-images.githubusercontent.com/37833135/55817628-338ee180-5af5-11e9-955a-72777d795be8.png)
![image](https://user-images.githubusercontent.com/37833135/55817923-ccbdf800-5af5-11e9-9e4b-bbedf4a8c7cd.png)

You still target a creature you want to use for evolution, but you don't spend any mana and you place the monster in another zone instead of using the same zone, and the pre-evolution monster isn't attached.

**Comment by Hello23-Ygopro** [comment]
It's probably caused by another typo. `g` should be `g2`: https://github.com/Hello23-Ygopro/ygopro-dm/blob/bf726695cd62766c968d28315e9d42f14356f91d/expansions/utility_dmtcg.lua#L1296

**Comment by Hello23-Ygopro** [comment]
[This commit](https://github.com/Hello23-Ygopro/ygopro-dm/commit/cc9b9b1c9b579864ce93d4fa4d7f19051d5fc9bf) should fix the error.
