### ISSUE TITLE
Factory Shell Q script error

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#14]
![image](https://user-images.githubusercontent.com/37833135/55821250-545b3500-5afd-11e9-975d-23b6833ec63d.png)

happened on summon. (Also happens on summon of any Survivor monster while Factory Shell Q is on the field)

**Comment by Hello23-Ygopro** [comment]
I couldn't reproduce an error. Here's a list of things I tested in puzzle mode on YGOPro Percy:
- Summoned _Factory Shell Q_ while I had no other creatures
- Summoned _Factory Shell Q_ while I had valid search targets in my deck
- Summoned _Factory Shell Q_ while I had no valid search targets in my deck
- Repeated the above for _Gigaling Q_
- Summoned _Factory Shell Q_ while I had _Gigaling Q_ on the field
- Summoned _Gigaling Q_ while _Factory Shell Q_ was on the field

Do you know what's on line 74 in YGOPro 2's `utility.lua` file?

**Comment by szefo09** [comment]
https://github.com/szefo09/ygopro-dm/blob/master/expansions/script/utility.lua
here's the utility.lua script used.

**Comment by Hello23-Ygopro** [comment]
> 74: 2 Parameters are needed.

1. Is this the only error you're getting?
2. Are all your YGOPro-DM scripts up to date?
3. Have you tried using Survivors in YGOPro 1? If so, are you getting any errors?
4. Since the issue is Survivor-related, do you know if YGOPro 2 supports `EFFECT_TYPE_GRANT`? If not, I wouldn't recommend using it because in that case it would be outdated and incompatible with YGOPro-DM.
5. There are many other cards in the screenshot and according to the error they may be the cause. I would start looking at those that are using the `aux.AND` function.

**Comment by szefo09** [comment]
1) Seems like it's the only error I'm getting on the server related to that card..
![image](https://user-images.githubusercontent.com/37833135/55835533-ae1f2780-5b1c-11e9-99c0-58a63bd6e107.png)

2) I always try to merge and force copy all the scripts that  you add.
3) I just tried to use it on KoishiPro simulator, but seems like it's the same. (Maybe it's something wrong with my utility.lua, I try to use the newest available on Fluoro's repo with a slight modification.)
![image](https://user-images.githubusercontent.com/37833135/55835729-e6bf0100-5b1c-11e9-95c6-764a984b2597.png)

4) YGOPro2 has no offline/LAN mode, so I'm hosting a ygopro-dm server to connect to and play. 
I am also hosting a regular ygopro server using files made by Koishi (purerosefallen on github). People using YGOPro 1 and YGOPro2 play on it, so I think Pro2 supports it.

**Comment by Hello23-Ygopro** [comment]
_Factory Shell Q_ uses the `dm.SendtoHandOperation` function. Here's the line that could be causing the error:
https://github.com/Hello23-Ygopro/ygopro-dm/blob/5068f39c932ed62203d4f6053a0bbb83f1365bfd/expansions/utility_dmtcg.lua#L3081

Also, I don't know if it will make a difference but try changing your `Auxiliary.AND` and `Auxiliary.OR` functions to:
```
function Auxiliary.AND(...)
	local funs={...}
	return	function(...)
				for _,f in ipairs(funs) do
					if not f(...) then return false end
				end
				return true
			end
end
```
```
function Auxiliary.OR(...)
	local funs={...}
	return	function(...)
				for _,f in ipairs(funs) do
					if f(...) then return true end
				end
				return false
			end
end
```

**Comment by szefo09** [comment]
![image](https://user-images.githubusercontent.com/37833135/55837816-b7ab8e00-5b22-11e9-9c04-f6a2e001e84f.png)

After the change line error has changed to 73

**Comment by Hello23-Ygopro** [comment]
I don't know... try the following:
1. Move `utility.lua` (not `utility_dmtcg.lua`) out of expansions/script if it's there.

2. If you still get the error, open `utility_dmtcg.lua` and add `PLAYER_OWNER=nil` under `EFFECT_INDESTRUCTIBLE_BATTLE=EFFECT_INDESTRUCTABLE_BATTLE`.

3. If you still get the error, open `c24006097.lua` and replace everything with:
```
--Factory Shell Q
local dm=require "expansions.utility_dmtcg"
local scard,sid=dm.GetID()
function scard.initial_effect(c)
	dm.EnableCreatureAttribute(c)
	--survivor (search) (to hand)
	dm.AddSingleComeIntoPlayEffect(c,0,nil,dm.HintTarget,scard.thop)
	dm.AddStaticEffectSingleComeIntoPlay(c,0,nil,dm.HintTarget,scard.thop,LOCATION_ALL,0,scard.thtg)
end
scard.duel_masters_card=true
function scard.thop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SELECTMSG,tp,DM_HINTMSG_ATOHAND)
	local g=Duel.SelectMatchingCard(tp,Card.DMIsRace,tp,LOCATION_DECK,0,0,1,nil,DM_RACE_SURVIVOR)
	if g:GetCount()>0 then
		Duel.SendtoHand(g,nil,REASON_EFFECT)
		Duel.ConfirmCards(1-tp,g)
	end
end
function scard.thtg(e,c)
	return c~=e:GetHandler() and c:DMIsRace(DM_RACE_SURVIVOR)
end
```

**Comment by szefo09** [comment]
3) Worked! 
![image](https://user-images.githubusercontent.com/37833135/55839104-0c510800-5b27-11e9-8a0c-60d51583ea32.png)

**Comment by Hello23-Ygopro** [comment]
It looks like `dm.SendtoHandOperation` was the problem. You may get the same error in the future.

To confirm that `aux.AND` was causing the error, in `utility_dmtcg.lua`, you can replace
`local g=Duel.GetMatchingGroup(aux.AND(Card.IsAbleToHand,f),tp,s,o,ex,table.unpack(funs))`
with:
`local g=Duel.GetMatchingGroup(f,tp,s,o,ex,table.unpack(funs))`

I don't know why that line specifically gives you an error.

**Comment by Hello23-Ygopro** [comment]
It looks like `dm.SendtoHandOperation` was the problem. You may get the same error in the future.

To confirm that `aux.AND` was causing the error, in `utility_dmtcg.lua`, you can replace
`local g=Duel.GetMatchingGroup(aux.AND(Card.IsAbleToHand,f),tp,s,o,ex,table.unpack(funs))`
with:
`local g=Duel.GetMatchingGroup(f,tp,s,o,ex,table.unpack(funs))`

I don't know why that line specifically gives you an error.

**Comment by Hello23-Ygopro** [comment]
It looks like `dm.SendtoHandOperation` was the problem. You may get the same error in the future.

To confirm that `aux.AND` was causing the error, in `utility_dmtcg.lua`, you can replace
`local g=Duel.GetMatchingGroup(aux.AND(Card.IsAbleToHand,f),tp,s,o,ex,table.unpack(funs))`
with:
`local g=Duel.GetMatchingGroup(f,tp,s,o,ex,table.unpack(funs))`

I don't know why that line gives you an error.

**Comment by szefo09** [comment]
So I restored the original script for Factory Shell Q and changed the line you've mentioned in `utility_dmtcg.lua`, error changed now to this: 
![image](https://user-images.githubusercontent.com/37833135/55859931-65468d80-5b73-11e9-9e04-ca436a8124e8.png)

It doesn't say the line anymore...

**Comment by szefo09** [comment]
I've also added the `aux.AND` to check if it's working in the card's code you've sent, and it seems to work fine here. I have no idea why the `Auxiliary.SendtoHandOperation` causes the issue with this card.

```--Factory Shell Q
local dm=require "expansions.utility_dmtcg"
local scard,sid=dm.GetID()
function scard.initial_effect(c)
	dm.EnableCreatureAttribute(c)
	--survivor (search) (to hand)
	dm.AddSingleComeIntoPlayEffect(c,0,nil,dm.HintTarget,scard.thop)
	dm.AddStaticEffectSingleComeIntoPlay(c,0,nil,dm.HintTarget,scard.thop,LOCATION_ALL,0,scard.thtg)
end
scard.duel_masters_card=true
function scard.thop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SELECTMSG,tp,DM_HINTMSG_ATOHAND)
	local g=Duel.SelectMatchingCard(tp,aux.AND(Card.IsAbleToHand,Card.DMIsRace),tp,LOCATION_DECK,0,0,1,nil,DM_RACE_SURVIVOR)
	if g:GetCount()>0 then
		Duel.SendtoHand(g,nil,REASON_EFFECT)
		Duel.ConfirmCards(1-tp,g)
	end
end
function scard.thtg(e,c)
	return c~=e:GetHandler() and c:DMIsRace(DM_RACE_SURVIVOR)
end```

**Comment by Hello23-Ygopro** [comment]
> 2 Parameters are needed.

I just started getting this error too. I don't know what caused it, but the line it listed is `local funs={...}` in the following function in `utility.lua`.
```
function Auxiliary.AND(...)
	local funs={...}
	return	function(...)
				for _,f in ipairs(funs) do
					if not f(...) then return false end
				end
				return true
			end
end
```

**Comment by Hello23-Ygopro** [comment]
[This commit](https://github.com/Hello23-Ygopro/ygopro-dm/commit/eacc227aab36d91c78cc76a51676b9043eed76ac) caused the error.

In `c24006097.lua`, replace
`dm.SendtoHandOperation(PLAYER_SELF,Card.DMIsRace,LOCATION_DECK,0,0,1,true,DM_RACE_SURVIVOR)`
with:
```
dm.SendtoHandOperation(PLAYER_SELF,Card.DMIsRace,LOCATION_DECK,0,0,1,true,nil,DM_RACE_SURVIVOR)
```
It was missing the exclusion parameter.

**Comment by szefo09** [comment]
Thank you for the fix! It works now
