### ISSUE TITLE
c24000000.lua line 371 error

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#2]
Hey there! I've been trying to test out your awesome work and when I hosted myself a server with the ygopro-dm (using ocgcore 0x1349) after a few rounds I've started getting multiples of those errors.

` [string \"./script/c24000000.lua\"]:371: attempt to call a nil value (method 'GetLabelObject')\n[string \"./script/c24000000.lua\"]:371: attempt to call a nil value (method 'GetLabelObject')
`
Am I missing something?

**Comment by szefo09** [comment]
What I've did: 
Replaced the lflist and strings, removed all scripts, copied scripts from your script folder, added back utility.lua and constant.lua, renamed cards-dm.cdb to cards.cdb, replaced cards.cdb, added cards-dm-vg to expansions folder, added utility_dmtcg.lua and constant_dmtcg.lua to expansions, launched the server.

**Comment by szefo09** [comment]
![image](https://user-images.githubusercontent.com/37833135/55489095-971a9a00-5631-11e9-81fb-1ccffdd21306.png)

**Comment by LordOfNightmares** [comment]
line 366 `e2:SetReset(RESET_EVENT+PHASE_END)` needs RESET_PHASE
`e2:SetReset(RESET_EVENT+RESET_PHASE+PHASE_END)`

**Comment by Hello23-Ygopro** [comment]
Wow, I hadn't noticed that after all this time... thank you! This might've fixed it: https://github.com/Hello23-Ygopro/ygopro-dm/commit/53a152a3e8bc40e3105b65bf999593cd1782aa87
