### ISSUE TITLE
Issue with Relentless Blitz

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#20]
![image](https://user-images.githubusercontent.com/37833135/56224873-a0aff300-6070-11e9-89bd-51b02fdd28fe.png)

While attacking during the turn the Relentless Blitz (2400941) was activated, script errors appear.

**Comment by Hello23-Ygopro** [comment]
Did [this patch](https://github.com/Hello23-Ygopro/ygopro-dm/commit/93a1bb5fc8ad41be24537bec1f4eb90045bc7f96) fix the error?
