### ISSUE TITLE
Monsters drawn chain and allow you to summon themselves instantly

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#22]
After implementing the newest commit this happens for both players when they draw a monster, If you press yes, the monster gets summoned for no cost: 
![image](https://user-images.githubusercontent.com/37833135/56393394-8f174880-6234-11e9-9ab6-e8bee5d20a44.png)

**Comment by Hello23-Ygopro** [comment]
Probably because there was a missing condition function: https://github.com/Hello23-Ygopro/ygopro-dm/commit/c9458a2befb6c90dec1cac3f2967779719c7f49a

**Comment by szefo09** [comment]
yeah, the new commit indeed fixed that, but now any shield acts as shield trigger: 
![image](https://user-images.githubusercontent.com/37833135/56395618-95f58980-623b-11e9-9646-cd880053723d.png)

**Comment by szefo09** [comment]
I've reverted the PRs for now, it's possible that the cards have to have those `dm.AddShieldTriggerCastEffect` parts or too many things go wrong...

**Comment by Hello23-Ygopro** [comment]
I think I know what's wrong. Due to `dm.AddShieldTriggerCastEffect` being removed, any broken shield can now trigger because there's no check for `c:IsHasEffect(DM_EFFECT_SHIELD_TRIGGER)`. I'll need to add a check for that effect to the shield trigger condition.
