### ISSUE TITLE
Can't summon vortex evolution using cards like Innocent Hunter, Blade of All

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#23]
I may be unaware of something here, but I control both a fire bird monster and Innocent Hunter on the field, and I have green and red mana for Avatar of Unity, but the game doesn't allow me to summon it.
![image](https://user-images.githubusercontent.com/37833135/56511871-00eddb80-652e-11e9-9355-d9843b98bafe.png)

**Comment by Hello23-Ygopro** [comment]
[This patch](https://github.com/Hello23-Ygopro/ygopro-dm/commit/a5cb95edab07168c8666efc849dacab5ea1b433d) should fix the interaction with _Innocent Hunter, Blade of All_.

According to its rulings, it can only substitute 1 of the creatures.
https://duelmasters.fandom.com/wiki/Innocent_Hunter,_Blade_of_All/Rulings

Also, looking at your screenshot, if you didn't have any cost reducing or civilization adding effects applied:
1. You might not have had enough untapped mana (6).
2. You might not have had enough untapped mana colors (1 blue + 1 black).
