### ISSUE TITLE
Monsters returned to field by the effect of Soul Pheonix, Avatar of Unity are placed on the field either face-down attack or face-down defense position. 

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#24]
The game asks you to choose the position, but both seem to lock the creatures into broken state.
The Pheonix was returned to hand by the effect of Aqua surfer/Spiral gate.
![image](https://user-images.githubusercontent.com/37833135/56517659-bbd1a580-653d-11e9-8d7d-f460f6160a71.png)

![image](https://user-images.githubusercontent.com/37833135/56517608-9e044080-653d-11e9-9e7c-c1fe20a79fd5.png)
![image](https://user-images.githubusercontent.com/37833135/56517611-a197c780-653d-11e9-9015-3db504d527e5.png)

Also, when the Pheonix is returned to the top of the deck by the effect of Corile, the effect never activates.

**Comment by Hello23-Ygopro** [comment]
> The game asks you to choose the position, but both seem to lock the creatures into broken state

Try changing `c:GetPosition()` to `c:GetPreviousPosition()` here:
https://github.com/Hello23-Ygopro/ygopro-dm/blob/a5cb95edab07168c8666efc849dacab5ea1b433d/expansions/script/c24012005.lua#L29

> Also, when the Pheonix is returned to the top of the deck by the effect of Corile, the effect never activates

I'm still trying to find a way to make it work. It seems that I need to register _Soul Phoenix's_ state (position and all its attached materials) before it enters the deck.

The only other thing that's not implemented, is its current continuous effect isn't a substitute effect, meaning if an effect destroys _Soul Phoenix_, it shouldn't count as being destroyed. This should also apply to all other removal effects.

**Comment by szefo09** [comment]
After merging the fix and checking just now, when the Soul Pheonix, Avatar of Unity is returned to hand (by the effect of Aqua Surfer/Spiral Gate) the materials are not resummoned and they stay in hand. 
![image](https://user-images.githubusercontent.com/37833135/56601248-eb92b300-65fa-11e9-8110-671050f8c0f9.png)

Destroying the card with Terror pit however worked out as expected, resummoning the materials used for the summon.

**Comment by Hello23-Ygopro** [comment]
> After merging the fix and checking just now, when the Soul Pheonix, Avatar of Unity is returned to hand (by the effect of Aqua Surfer/Spiral Gate) the materials are not resummoned and they stay in hand.

This is probably why: https://github.com/Hello23-Ygopro/ygopro-dm/blob/75c39b3730235bc9edc9bb008beb2241e24a6244/expansions/utility_dmtcg.lua#L475

There's a similar issue when using _Pangaea's Song_ - the materials will follow the evolution creature. Each `Duel` function that sends a creature to another location must be updated to check if a creature has the weird workaround "leave replace" effect _Soul Phoenix_ has, and if it does its materials should be excluded from leaving.

**Comment by Hello23-Ygopro** [comment]
> After merging the fix and checking just now, when the Soul Pheonix, Avatar of Unity is returned to hand (by the effect of Aqua Surfer/Spiral Gate) the materials are not resummoned and they stay in hand.

This using [this patch](https://github.com/Hello23-Ygopro/ygopro-dm/commit/7b938aebf16c6d667d2fe3a18407849a441164ed).

Now _Soul Phoenix_ still has 3 issues:
☐ The effect of Soul Phoenix leaving the battle zone is not substituted or replaced (e.g. `EVENT_LEAVE_FIELD_REPLACE`)
☐ The effect of Soul Phoenix leaving the battle zone is not applied when it is returned to the deck
☐ The effect of Soul Phoenix leaving the battle zone is not applied when it is added to the shield zone

**Comment by Hello23-Ygopro** [comment]
@szefo09, What happens to _Soul Phoenix_'s materials when _Corile_ puts _Soul Phoenix_ on top of the deck?
1. They are banished.
2. They are sent to Yugioh's graveyard.
3. They are returned on top of the deck.
3. They stay in the battle zone in the position _Soul Phoenix_ was in before it left the battle zone.

**Comment by szefo09** [comment]
After your fix, it seems they now get summoned onto the field correctly (the game asked me to select place for them) 
![image](https://user-images.githubusercontent.com/37833135/56929248-6404e280-6ad9-11e9-9f3a-f66d2297054a.png)

![image](https://user-images.githubusercontent.com/37833135/56929212-4cc5f500-6ad9-11e9-8d20-1815db093333.png)

**Comment by Hello23-Ygopro** [comment]
Thanks, I'll close this because I recently included the remaining issues [here](https://github.com/Hello23-Ygopro/ygopro-dm/issues/25). For example, creatures with leave effects won't trigger when added to the shields.
