### ISSUE TITLE
DM Promotional and Game original artworks missing from the repository

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#26]
Hey, it seems that those card's artworks aren't present in the pic repository. 
It's a minor issue, and if it's not possible to get them, I'll understand. But I'm just curious if they'll be available in the future. 

![image](https://user-images.githubusercontent.com/37833135/57402301-4cafae80-71d7-11e9-9592-7bef15276355.png)
![image](https://user-images.githubusercontent.com/37833135/57402305-4faa9f00-71d7-11e9-92dd-501bf9907628.png)
![image](https://user-images.githubusercontent.com/37833135/57402310-51746280-71d7-11e9-95c1-0d9119781a12.png)

**Comment by Hello23-Ygopro** [comment]
I haven't found any consistent card images for the English promotional cards yet. And the wiki doesn't have card images for all game original cards.

**Comment by szefo09** [comment]
Hey, I found someone sharing a template for DM cards: http://dmreborn.forumieren.com/t313-duel-masters-template

Link to template: https://www.mediafire.com/file/fnvo74oaoeyl7qo/DM_Template.psd/file
Link to fonts: https://www.mediafire.com/file/0ti9ht43aoocxsf/Fonts.rar/file

It's an alternative :)

**Comment by Hello23-Ygopro** [comment]
Will [these](https://mega.nz/#F!5RAFSIYb!nF8pJNkmZk4TzwMGtiX8Xw) do?
- 24001-24025 don't have artwork
- 24026-24030 are in Japanese
- All promo cards are in English and have the modified gen 3 layout

**Comment by szefo09** [comment]
Thanks 👍 they will be better distinguished this way!
![image](https://user-images.githubusercontent.com/37833135/57531844-b1cfe500-733a-11e9-964c-9f883b5ad742.png)
