### ISSUE TITLE
Monster summoned with SoulSwap can attack the turn it was summoned. 

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#28]
I summoned Factory Shell Q using Soul swap on Bronze-arm tribe that was summoned last turn, went into battle phase, and was able to attack with it on the same turn.

**Comment by Hello23-Ygopro** [comment]
Did you return a _Bronze-Arm Tribe_ in your monster zone or your opponent's monster zone?

**Comment by szefo09** [comment]
In my monster zone, here, I reproduced it with Wind axe (it destroyed opponet's blocker on summon and is able to attack):
![image](https://user-images.githubusercontent.com/37833135/57478156-8bf30380-729a-11e9-930e-eeb6ce50f96a.png)
![image](https://user-images.githubusercontent.com/37833135/57478161-90b7b780-729a-11e9-8437-72098990bec0.png)

**Comment by Hello23-Ygopro** [comment]
It appears to be another rule-related bug. It seems to be fixed when I change `ep` to `tp` here:
https://github.com/Hello23-Ygopro/ygopro-dm/blob/b7bfb5a/expansions/script/c24000000.lua#L379

**Comment by szefo09** [comment]
Yeah, changing that `ep` to `tp` indeed stopped the soul-swapped monster to be able to attack the turn it was summoned. Hope it won't break anything else :) 

A bit of offtop: There's a reddit post showcasing your project on /r/DuelMasters

**Comment by Hello23-Ygopro** [comment]
It was like that when I started the mod. I don't know why I changed it to pass the event player... If it did break something, then we'll notice it with another summoning sickness bug in the future, but I doubt it did. Your reports are helpful, as I don't play this mod as often as I used to.
