### ISSUE TITLE
Duels aren't ended properly

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#29]
After attacking with a monster while the opponent has no shield it appeared that the opponent didn't took any damage, game hasn't properly registered that an opponent with no shields was attacked,  and the game hasn't ended.

**Comment by Hello23-Ygopro** [comment]
Thanks for the report. I mistakenly changed the effect it to an effect that affects a player with this commit: https://github.com/Hello23-Ygopro/ygopro-dm/commit/5085e1f92a757475aab1426559a8a585e6df85e0#diff-e9b7cf00659d8af67065e41421794ee8
It should be fixed now.
