### ISSUE TITLE
The game does not end after attacking a player

### ISSUE THREAD

**Issue by Tadeii** [Hello23-Ygopro/ygopro-dm#30]
As the title says. This is the case in both Quick Duel and Join Game mode.

**Comment by Hello23-Ygopro** [comment]
I've found the bug: https://github.com/Hello23-Ygopro/ygopro-dm/blob/1441786/expansions/script/c24000000.lua#L200

The battle damage prevention should only apply to the creatures in the battle zone, not the players.
