### ISSUE TITLE
Monsters summoned by one of the players don't suffer summoning sickness.

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#31]
![image](https://user-images.githubusercontent.com/37833135/57533215-81d61100-733d-11e9-9a9b-846368737fa5.png)
![image](https://user-images.githubusercontent.com/37833135/57533218-84386b00-733d-11e9-9bbb-400f07eee5e3.png)

All I did this turn is summoning him, doesn't seem like there are any effects that allow it to attack the turn it was summoned.
It also happened on my next turn when I summoned Mist Rias, but my opponent couldn't attack with Gajirabute that he just summoned.
![image](https://user-images.githubusercontent.com/37833135/57533488-2d7f6100-733e-11e9-8de2-034dd37b97f7.png)

**Comment by Hello23-Ygopro** [comment]
You have [this commit](https://github.com/Hello23-Ygopro/ygopro-dm/commit/4d5644afc43889be716458294a2154df5dffa09b) applied, right? It might be the cause. Also, did this happen in a LAN duel or in puzzle mode?

**Comment by Hello23-Ygopro** [comment]
I didn't get the same issue. See if changing `tp` to `e:GetHandlerPlayer()` makes a difference here:
https://github.com/Hello23-Ygopro/ygopro-dm/blob/4d5644a/expansions/script/c24000000.lua#L379

**Comment by szefo09** [comment]
Hey,yeah, I try to keep stuff up to date on my DM YGOPro server, I do have that commit applied, and  it happended on normal duel.

**Comment by Hello23-Ygopro** [comment]
I didn't get the same issue. See if changing tp to e:GetHandlerPlayer() makes a difference here:
https://github.com/Hello23-Ygopro/ygopro-dm/blob/4d5644a/expansions/script/c24000000.lua#L379

**Comment by szefo09** [comment]
kk, after changing this line here like so:
![image](https://user-images.githubusercontent.com/37833135/57537366-691e2900-7346-11e9-8c7b-b832fc67b55b.png)
I've made a quick duel after that change. I summoned Melnia on one side, it couldn't attack the turn it was summoned.
But then I summoned it on the other side, and it can attack the turn it was summoned.
![image](https://user-images.githubusercontent.com/37833135/57537437-8ce16f00-7346-11e9-925f-50a15d90e01e.png)

**Comment by Hello23-Ygopro** [comment]
Try changing `tp` to `Duel.GetTurnPlayer()` on the same line. Does it make a difference?

**Comment by szefo09** [comment]
Hmm, the `Duel.GetTurnPlayer()` may have fixed it, becase after changing it and playing another duel, it seems that both sides are affected by summoning sickness again.

**Comment by Hello23-Ygopro** [comment]
Yeah, I don't think `c:IsControler()` should be there. It's causing some problems. I think I initially included it to prevent the a summoned monster from getting summoning sickness from both rule cards.

**Comment by Hello23-Ygopro** [comment]
See if this fix worked: https://github.com/Hello23-Ygopro/ygopro-dm/commit/78050eba3aa67a3e3cee0aef4f2a2dff9cfa8c9f
