### ISSUE TITLE
Jagalzor's ability seems to be coded wrong

### ISSUE THREAD

**Issue by Tadeii** [Hello23-Ygopro/ygopro-dm#32]
This issue was discovered by Szefo09. He noticed that after Jagalzor's Turbo Rush effect was in play and of creatures controlled by him broke a shield that activated Soulswap and put a new creature for him (the Poisonous Mushroom) it didn't get the effect of Jagalzor, thus couldn't attack with it. The correct outcome should be giving the swapped creature a speed attacker. I'm attaching a screenshot to better illustrate the situation. 
![jagalzor-issue](https://user-images.githubusercontent.com/35153025/57540364-daf97100-734c-11e9-8412-c17abe9f488d.png)

**Comment by szefo09** [comment]
Looking at Jagalzor's script it seems to simply iterate by each monster the player controls. 
Seems that the correct ruling is more in line of setting a continous like effect until the end of the turn to give each monster on the player's field a speed attacker attribute.

**Comment by Hello23-Ygopro** [comment]
Thanks, try this version: https://github.com/Hello23-Ygopro/ygopro-dm/commit/5d2360bfe8316ec16526705aeacc2f6eaf1d1527

**Comment by Hello23-Ygopro** [comment]
According to [its rulings](https://duelmasters.fandom.com/wiki/Magmadragon_Jagalzor/Rulings), the "Speed Attacker" continuous effect is suppsoed to reset when Jagalzor leaves the battle zone, so it's not entirely fixed yet.

**Comment by szefo09** [comment]
Yeah, I see. So that cont. Effect should go away if Jagalzor that activated it is removed from the field.

**Comment by szefo09** [comment]
ok, after some testing, all the mentioned interactions seem to work correctly
