### ISSUE TITLE
Issue with Shield Triggered Ghost Touch

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#5]
Shield gets destroyed. Under it there was Ghost Touch. Activate Ghost Touch's shield trigger effect.
Expected result: Opponent discards a random card.
Current result: The player that activated Ghost Touch discards a random card.

**Comment by Hello23-Ygopro** [comment]
I noticed it too. It might be because the hand ranges are reversed in each script where `dm.DiscardOperation` is used.
https://github.com/Hello23-Ygopro/ygopro-dm/blob/1f6678516beda102bd5df3c60b222d37ddb4caa3/expansions/script/c24001054.lua#L9

**Comment by szefo09** [comment]
Yes, it appears that most of the discard effects sometimes affect the owner instead of the opponent. For example the discard effect of Horrid Worm

**Comment by Hello23-Ygopro** [comment]
This might've fixed it: https://github.com/Hello23-Ygopro/ygopro-dm/commit/0ef4d2a048987750fe0ea75581632d06d983def0

I don't know why it only _sometimes_ happened. The functions `Duel.DiscardHand` and `Duel.RandomDiscardHand` might also have some bugs.

**Comment by szefo09** [comment]
Unfortunately the issue was not fixed, activating Ghost Touch from hand still makes the player discard the card instead of the opponent. Here's a replay showcasing this issue as well as issue #7 
[dm_ygopro_issues.zip](https://github.com/Hello23-Ygopro/ygopro-dm/files/3045396/dm_ygopro_issues.zip)

**Comment by Hello23-Ygopro** [comment]
It looks like the discarding player changed depending on the situation.

Here's another attempted fix: https://github.com/Hello23-Ygopro/ygopro-dm/commit/806c8af58baad41ffa4e27d8251c465a2c8500b8

**Comment by szefo09** [comment]
Seems like the fix is working! Thank you!
