### ISSUE TITLE
issue function Auxiliary.NoShieldsCondition(p)

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#6]
When summoning Vashuna, Sword Dancer (24005034)
I get a script error 

`./expansions/utility_dmtcg.lua:3357: attempt to perform arithmetic on a nil value (local 'tp')"`

Seems like some functions don't know about turn player

**Comment by Hello23-Ygopro** [comment]
It might be because it doesn't have `local tp=e:GetHandlerPlayer()` included for continuous effects, like _Vashuna, Sword Dancer's_.

This might've fixed it: https://github.com/Hello23-Ygopro/ygopro-dm/commit/259ff19880d8300147316b27b2e125cd738e17d2
