### ISSUE TITLE
Some monster can be special summoned with less mana than their requirement

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#7]
![image](https://user-images.githubusercontent.com/37833135/55586440-38d0e280-5729-11e9-9d2d-00a7e4c1353b.png)

Only 4 mana (The monster wanted to summon even with only 1 mana available), yet 5 cost monster can be summoned.

**Comment by Hello23-Ygopro** [comment]
_Gigaberos_ and _Gigagiele's_ mana cost are 0 in the database.

This might've fixed it: https://github.com/Hello23-Ygopro/ygopro-dm/commit/6af576eaad295e11d4a70f01be14dcf2033a627e
