### ISSUE TITLE
Terradragon Gamiratar effect summons opponent's monster into your zone

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#8]
![image](https://user-images.githubusercontent.com/37833135/55683047-6e4d1a00-593b-11e9-8471-75ddfec40bdb.png)
![image](https://user-images.githubusercontent.com/37833135/55683048-70af7400-593b-11e9-83e2-d4a954051875.png)

Opponent summons Terradragon, opponent chooses a monster, monster gets summoned to the opposite side of the field.

**Comment by Hello23-Ygopro** [comment]
There are plenty of issues with the `Auxiliary.TargetSendtoBattleTarget` and `Auxiliary.TargetSendtoBattleOperation` functions. This issue may take a while to fix because all these kinds of functions need to be fixed and improved.
