### ISSUE TITLE
Gigaberos doesn't destroy 2 of your creatures or destroys itself on summon

### ISSUE THREAD

**Issue by szefo09** [Hello23-Ygopro/ygopro-dm#9]
![image](https://user-images.githubusercontent.com/37833135/55683178-32b34f80-593d-11e9-8193-364b10da45dd.png)
![image](https://user-images.githubusercontent.com/37833135/55683180-347d1300-593d-11e9-8629-8f95531be140.png)

**Comment by Hello23-Ygopro** [comment]
This is similar to _Terradragon Gamiratar_. #8 I need to fix all the appropriate `Auxiliary` functions so this kind of issue doesn't happen again.

**Comment by Hello23-Ygopro** [comment]
There were many constants that didn't have the DM prefix, which caused some abilities to not properly resolve: https://github.com/Hello23-Ygopro/ygopro-dm/commit/366e0785143715a09802bff93787339246d7c4e2

**Comment by Hello23-Ygopro** [comment]
There were many constants that didn't have the DM prefix which caused some abilities to not properly resolve: https://github.com/Hello23-Ygopro/ygopro-dm/commit/366e0785143715a09802bff93787339246d7c4e2
